name: CD
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: |
          git fetch origin gh-pages
          git checkout gh-pages
      - run: git pull origin gh-pages --rebase
      - run: mkdocs gh-deploy
